version: "3.4"

# Development environment override
services:
  php:
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - logs:/srv/app/var/log
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line 
      # - /srv/app/var
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]
  ###< symfony/mailer ###

  ## WARNING : Execute this if it doesn't load  sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: sebp/elk
    volumes:
      - ./docker/logstash/:/etc/logstash/conf.d/
      - logs:/var/log/app
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
      - target: 9200
        published: 9200
        protocol: tcp
      - target: 5044
        published: 5044
        protocol: tcp

volumes:
  logs:
